export const mascotLinks = {
  happyLoo: [
    "/mascots/CALM_LOOPS_BALL.png",
    "/mascots/CALM_STANDING.png",
    "/mascots/CLAM_LOOPS.png",
    "/mascots/CUTE_LOOPS.png",
    "/mascots/DIVING_LOOPS.png",
    "/mascots/EXITED_LOOPS.png",
    "/mascots/HAPPY_JUMPING_LOOPS.png",
    "/mascots/HAPPY_LOOPS_ON_THE_FLOOR.png",
    "/mascots/ROLLING_LOOPS.png",
    "/mascots/RUNNING_LOOPS.png",
    "/mascots/SITTING_LOOPS.png",
    "/mascots/WALKING_LOOPS.png",
  ],
  sadLoo: [
    "/mascots/ANGRY_LOOPS.png",
    "/mascots/ANGRY_LOOPS_ON_THE_FLOOR.png",
    "/mascots/ATTACKING_LOOPS.png",
    "/mascots/DEPRESSES_LOOPS.png",
    "/mascots/FALLING_LOOPS.png",
    "/mascots/SAD_LOOPS.png",
    "/mascots/SAD_SETTING_LOOPS.png",
  ],
}
