/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileSettingsRouteImport } from './routes/profile_.settings'
import { Route as ProfileSettingsSecurityRouteImport } from './routes/profile_.settings_.security'
import { Route as ProfileSettingsPreferencesRouteImport } from './routes/profile_.settings_.preferences'
import { Route as ProfileSettingsEditProfileRouteImport } from './routes/profile_.settings_.edit-profile'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/profile_/settings',
  path: '/profile/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsSecurityRoute = ProfileSettingsSecurityRouteImport.update({
  id: '/profile_/settings_/security',
  path: '/profile/settings/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsPreferencesRoute =
  ProfileSettingsPreferencesRouteImport.update({
    id: '/profile_/settings_/preferences',
    path: '/profile/settings/preferences',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfileSettingsEditProfileRoute =
  ProfileSettingsEditProfileRouteImport.update({
    id: '/profile_/settings_/edit-profile',
    path: '/profile/settings/edit-profile',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/settings/edit-profile': typeof ProfileSettingsEditProfileRoute
  '/profile/settings/preferences': typeof ProfileSettingsPreferencesRoute
  '/profile/settings/security': typeof ProfileSettingsSecurityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/settings/edit-profile': typeof ProfileSettingsEditProfileRoute
  '/profile/settings/preferences': typeof ProfileSettingsPreferencesRoute
  '/profile/settings/security': typeof ProfileSettingsSecurityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/profile_/settings': typeof ProfileSettingsRoute
  '/profile_/settings_/edit-profile': typeof ProfileSettingsEditProfileRoute
  '/profile_/settings_/preferences': typeof ProfileSettingsPreferencesRoute
  '/profile_/settings_/security': typeof ProfileSettingsSecurityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/leaderboard'
    | '/login'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/profile/settings'
    | '/profile/settings/edit-profile'
    | '/profile/settings/preferences'
    | '/profile/settings/security'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/leaderboard'
    | '/login'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/profile/settings'
    | '/profile/settings/edit-profile'
    | '/profile/settings/preferences'
    | '/profile/settings/security'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/leaderboard'
    | '/login'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/profile_/settings'
    | '/profile_/settings_/edit-profile'
    | '/profile_/settings_/preferences'
    | '/profile_/settings_/security'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ProfileSettingsEditProfileRoute: typeof ProfileSettingsEditProfileRoute
  ProfileSettingsPreferencesRoute: typeof ProfileSettingsPreferencesRoute
  ProfileSettingsSecurityRoute: typeof ProfileSettingsSecurityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/settings': {
      id: '/profile_/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/settings_/security': {
      id: '/profile_/settings_/security'
      path: '/profile/settings/security'
      fullPath: '/profile/settings/security'
      preLoaderRoute: typeof ProfileSettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/settings_/preferences': {
      id: '/profile_/settings_/preferences'
      path: '/profile/settings/preferences'
      fullPath: '/profile/settings/preferences'
      preLoaderRoute: typeof ProfileSettingsPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/settings_/edit-profile': {
      id: '/profile_/settings_/edit-profile'
      path: '/profile/settings/edit-profile'
      fullPath: '/profile/settings/edit-profile'
      preLoaderRoute: typeof ProfileSettingsEditProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  ProfileSettingsEditProfileRoute: ProfileSettingsEditProfileRoute,
  ProfileSettingsPreferencesRoute: ProfileSettingsPreferencesRoute,
  ProfileSettingsSecurityRoute: ProfileSettingsSecurityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
